#!/bin/bash

echo "Merging intermediate postings"

cd tmp
for filename in postings-*.txt; do
    echo "Sorting $filename"
    # sort -t ' ' -k 1n -k 2n $filename > sorted-$filename
    sort -t ' ' -k 1,1 -k 2,2n $filename > sorted-$filename
done

echo "Merging to merged-postings.txt"
# sort -t ' ' -k 1n -k 2n -m sorted-postings-*.txt > merged-postings.txt
sort -t ' ' -k 1,1 -k 2,2n -m sorted-postings-*.txt > merged-postings.txt

rm sorted-postings-*.txt

echo "Merged intermediate postings"