#!/bin/bash

echo "$(date) - Merging intermediate postings"

cd tmp
for filename in postings-*.txt; do
    echo "$(date) - Sorting $filename"
    sort -t ' ' -k 1,1 -k 2,2n $filename > sorted-$filename
done

echo "$(date) - Merging to merged-postings.txt"
sort -t ' ' -k 1,1 -k 2,2n -m sorted-postings-*.txt > merged-postings.txt

rm sorted-postings-*.txt

echo "$(date) - Merged intermediate postings"